targets:
  $default:
    sources:
      - lib/**
      - graphql/**
      - pokemon.schema.graphql
    builders:
      artemis:
        options:
          fragments_glob: graphql/**.fragment.graphql
          schema_mapping:
            - schema: pokemon.schema.graphql
              queries_glob: graphql/big_query.query.graphql
              output: lib/graphql/big_query.dart
